package com.stormery.herbarium.screens;

public enum EnumTherapeuticProperties {
    ANTIBACTERIAL, ANTIPYRETIC, ANTISPASMODIC, ANTITUSSIVE, ASTRINGENTS,
    CARDIAC_INSUFFICIENCY, CARMINATIVE, CHOLAGOGUES,
    DEMULCENT, DIAPHORETIC, DIURETIC,
    EXPECTORANT, IMPROVING_DIGESTION,
    LAXATIVE, PROTECTIVE_SCREENING, SEDATIVE, SPASMOLYTIC,
    URINARY_TRACT_DISINFECTANT


}
