package com.stormery.herbarium.service;

/**
 * Created by Ayo on 2017-08-14.
 */

public enum EnumHerb {
    ALDER_BUCKTHORN, ALOE, ALTHEA, ANGELICA, ANISEED, BEARBERRY, BIRCH_TREE,
    CAROM,CHAMOMILE, COMMON_HOP, CRANBERRY,CORIANDER, DILL, ELDER, FLAX, GOLDEN_ROD,
    HAWTHORN, HELICHRYSUM, HORSETAIL, JUNIPER, KNOTGRASS,
    LAVENDER, LEMON_BALM, LOVAGE, MALLOW,
    PEPPERMINT, PLANTAGO_OVATA, POPLAR, PSYLLIUM, POKRZYWA, RHUBARB, RUMIANEK,
    SAGE, SENNA, ST_JOHNS_WORT,THYME, TILIA, WILLOW, VALERIAN,
    VIOLA_TRICOLOR, YARROW
}

